### ISSUE TITLE
cannot download twitterspace

### ISSUE THREAD

**Issue by TheGreatestNyanCat** [BANKA2017/twitter-monitor#11]
Hi, BANKA2017!
I am thankful to your blog post about twitter.

I found error about downloading/reading twitterspace.

now, my script's AudioSpaceId (graphql:audiospace) return error.
* I using fa0311/TwitterInternalAPIDocument for 'features' field.

Also, twitter-monitor has error now.
test spaceurl : https://twitter.com/i/spaces/1djGXldPqNyGZ

That spaceurl is ended. I know.
Yesterday, I can read information using twitter-monitor.
But. Cannot read that now using twitter-monitor.

<< graphql:audiospace response >>
{"errors":[{"message":"The following features cannot be null: rweb_video_timestamps_enabled","extensions":{"name":"BadRequestError","source":"Client","code":336,"kind":"Validation","tracing":{"trace_id":"**censored**"}},"code":336,"kind":"Validation","name":"BadRequestError","source":"Client","tracing":{"trace_id":"**censored**"}}]}

Thank you for read it.

**Comment by BANKA2017** [comment]
> The following features cannot be null: rweb_video_timestamps_enabled

This message means that the requested parameter is missing `rweb_video_timestamps_enabled`, you need to add `"rweb_video_timestamps_enabled":true` to the value of the request parameter `features`.

The reason for this situation is that the value of this parameter is located on the html of the web page. The update script did not process the html.

However, `rweb_video_timestamps_enabled` is not required in twitter monitor.

Hope this helps you.

**Comment by TheGreatestNyanCat** [comment]
@BANKA2017 Thanks for reply!
I'm find to way for fix.
I'll proceed in a direction that does not depend on the git (fa0311/TwitterInternalAPIDocument) anymore.
I'll try to fix that.
+ Thank you very much for creating the OAuth generator. It helped me a lot when I made the oauth_signature value.
