### ISSUE TITLE
homeline怎么办

### ISSUE THREAD

**Issue by web3dever** [BANKA2017/twitter-monitor#3]
是推主的主页时间线，这种应该要鉴权了吧，请问大佬怎么做到这种, 用curl复制能跑通

**Comment by BANKA2017** [comment]
鉴权部分包括 `cookie` 和 `header` 的 `x-csrf-token`。
- `cookie` 需要拿到 `auth_token` 和 `ct0`，这两个都是登录的时候给的，有效期一年多点
- `x-csrf-token` 的值只需要跟 `ct0` 一致即可

**Comment by web3dever** [comment]
> 

大佬，tg加不上，可否先打开限制

**Comment by BANKA2017** [comment]
>tg加不上

网站有tg群号 [tmtg_cn](https://t.me/tmtg_cn)

**Comment by n0099** [comment]
https://github.com/BANKA2017/twitter-monitor/commit/05764f3b25215ab21697e46cf99e3eff727505e9 既然 @BANKA2017 阁下早在[半年前](https://github.com/BANKA2017/twitter-monitor/commits/05764f3b25215ab21697e46cf99e3eff727505e9/apps/archiver/archive.mjs)就做完类似6年前[tbm](https://github.com/n0099/TiebaMonitor/blob/437444596b831fd0926ce05dcb0f01a93d36b6ba/c%23/crawler/src/Worker/ArchiveCrawlWorker.cs)引入的[近完整archive功能](https://github.com/Starry-OvO/aiotieba/issues/83#issuecomment-1384270489)，那阁下能帮隔壁前四叶群友dark495新疆东百人福建泉州小药娘推特小药娘小团体头子悦咚archive他的homeline吗 https://twitter.com/YueDongQwQ/status/1658611601979883521
