### ISSUE TITLE
twitter跟新问题

### ISSUE THREAD

**Issue by bestRunner** [BANKA2017/twitter-monitor#5]
请问定向用户采集和关键词搜索采集，目前依旧可以使用游客认证X-Guest-Token，进行数据采集嘛？

**Comment by BANKA2017** [comment]
是的，目前使用的是tweetdeck的bearer token。但搜索有随机返回空列表和结果不全的问题

**Comment by bestRunner** [comment]
> 是的

请问有相关API吗？我是一名java程序员，不太能看懂目前的代码

**Comment by bestRunner** [comment]
用户信息采集我看您使用的是：UserByRestId，UserByScreenName和1.1/users/show.json这三个接口进行采集的，但是我看这三个接口使用X-Guest-Token方式都不可以采集了

**Comment by BANKA2017** [comment]
大概是这些？

- 通用部分
  - authorization: Bearer AAAAAAAAAAAAAAAAAAAAAFQODgEAAAAAVHTp76lzh3rFzcHbmHVvQxYYpTw%3DckAlMINMjmCwxUcaXbAN4XqJVdgMJaHqNOFgPMK0zN1qLqLQCF
  - x-guest-token: <GUEST_TOKEN>
  - cookie: gt=<GUEST_TOKEN>;


- 定向用户采集

  目前我用的是客户端的API，缺点是 `count` 的值不可调，给的两个url区别只在是否返回回复，请求参数是一样的
  - Method: **GET**
  - URL: 
    - `https://api.twitter.com/graphql/3JNH4e9dq1BifLxAa3UMWg/UserWithProfileTweetsQueryV2`
    - `https://api.twitter.com/graphql/8IS8MaO-2EN6GZZZb8jF0g/UserWithProfileTweetsAndRepliesQueryV2`
  - Query
    - variables: 
      ```json
      {
          includeTweetImpression: true,
          includeHasBirdwatchNotes: false,
          includeEditPerspective: false,
          includeEditControl: true,
          count: <COUNT>,
          rest_id: <REST_ID>,
          includeTweetVisibilityNudge: true,
          autoplay_enabled: true,
          cursor: <CURSOR>
      }
      ```
    - features:
      ```json
      {
          "longform_notetweets_inline_media_enabled": true,
          "super_follow_badge_privacy_enabled": true,
          "longform_notetweets_rich_text_read_enabled": true,
          "super_follow_user_api_enabled": true,
          "unified_cards_ad_metadata_container_dynamic_card_content_query_enabled": true,
          "super_follow_tweet_api_enabled": true,
          "android_graphql_skip_api_media_color_palette": true,
          "creator_subscriptions_tweet_preview_api_enabled": true,
          "freedom_of_speech_not_reach_fetch_enabled": true,
          "creator_subscriptions_subscription_count_enabled": true,
          "tweetypie_unmention_optimization_enabled": true,
          "longform_notetweets_consumption_enabled": true,
          "subscriptions_verification_info_enabled": true,
          "blue_business_profile_image_shape_enabled": true,
          "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
          "super_follow_exclusive_tweet_notifications_enabled": true
      }
      ```

- 搜索
  
  目前在用旧版 Tweetdeck 用的 1.1 universal 接口，缺点是不稳定，经常返回空的推文列表，即使能返回列表也缺不少推文。

  没有 `cursor`，需要上下翻页就在 `<QUERY_STRING>` 结尾加上 ` since_id:<TWEET_ID>`（上） 或者 ` max_id:<TWEET_ID>`（下）

  - Method: **GET**
  - URL: `https://api.twitter.com/1.1/search/universal.json`
  - Query
    ```text
    q: <QUERY_STRING>
    count: <COUNT>
    modules: 'status'
    result_type: 'recent'
    pc: false
    ui_lang: 'en-US'
    cards_platform: 'Web-13'
    include_entities: 1
    include_user_entities: 1
    include_cards: 1
    send_error_codes: 1
    tweet_mode: 'extended'
    include_ext_alt_text: true
    include_reply_count: true
    ```

**Comment by bestRunner** [comment]
> 大概是这些？
> 
> * 通用部分
>   
>   * authorization: Bearer AAAAAAAAAAAAAAAAAAAAAF7aAAAAAAAASCiRjWvh7R5wxaKkFp7MM%2BhYBqM%3DbQ0JPmjU9F6ZoMhDfI4uTNAaQuTDm2uO9x3WFVr2xBZ2nhjdP0
>   * x-guest-token: <GUEST_TOKEN>
>   * cookie: gt=<GUEST_TOKEN>;
> * 定向用户采集
>   目前我用的是客户端的API，缺点是 `count` 的值不可调，给的两个url区别只在是否返回回复，请求参数是一样的
>   
>   * Method: **GET**
>   * URL:
>     
>     * `https://api.twitter.com/graphql/3JNH4e9dq1BifLxAa3UMWg/UserWithProfileTweetsQueryV2`
>     * `https://api.twitter.com/graphql/8IS8MaO-2EN6GZZZb8jF0g/UserWithProfileTweetsAndRepliesQueryV2`
>   * Query
>     
>     * variables:
>       ```json
>       {
>           includeTweetImpression: true,
>           includeHasBirdwatchNotes: false,
>           includeEditPerspective: false,
>           includeEditControl: true,
>           count: <COUNT>,
>           rest_id: <REST_ID>,
>           includeTweetVisibilityNudge: true,
>           autoplay_enabled: true,
>           cursor: <CURSOR>
>       }
>       ```
>     * features:
>       ```json
>       {
>           "longform_notetweets_inline_media_enabled": true,
>           "super_follow_badge_privacy_enabled": true,
>           "longform_notetweets_rich_text_read_enabled": true,
>           "super_follow_user_api_enabled": true,
>           "unified_cards_ad_metadata_container_dynamic_card_content_query_enabled": true,
>           "super_follow_tweet_api_enabled": true,
>           "android_graphql_skip_api_media_color_palette": true,
>           "creator_subscriptions_tweet_preview_api_enabled": true,
>           "freedom_of_speech_not_reach_fetch_enabled": true,
>           "creator_subscriptions_subscription_count_enabled": true,
>           "tweetypie_unmention_optimization_enabled": true,
>           "longform_notetweets_consumption_enabled": true,
>           "subscriptions_verification_info_enabled": true,
>           "blue_business_profile_image_shape_enabled": true,
>           "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
>           "super_follow_exclusive_tweet_notifications_enabled": true
>       }
>       ```
> * 搜索
>   目前在用旧版 Tweetdeck 用的 1.1 universal 接口，缺点是不稳定，经常返回空的推文列表，即使能返回列表也缺不少推文。
>   没有 `cursor`，需要上下翻页就在 `<QUERY_STRING>` 结尾加上 ` since_id:<TWEET_ID>`（上） 或者 ` max_id:<TWEET_ID>`（下）
>   
>   * Method: **GET**
>   * URL: `https://api.twitter.com/1.1/search/universal.json`
>   * Query
>     ```
>     q: <QUERY_STRING>
>     count: <COUNT>
>     modules: 'status'
>     result_type: 'recent'
>     pc: false
>     ui_lang: 'en-US'
>     cards_platform: 'Web-13'
>     include_entities: 1
>     include_user_entities: 1
>     include_cards: 1
>     send_error_codes: 1
>     tweet_mode: 'extended'
>     include_ext_alt_text: true
>     include_reply_count: true
>     ```

好的，谢谢您，我看一下

**Comment by BANKA2017** [comment]
> 使用的是：UserByRestId，UserByScreenName和1.1/users/show.json这三个接口进行采集的

这三个是以前的网页用的接口，前两个可以用我上面给的那个 `bearer token` 获取 `guest_token `来调用，应该是没有问题的，我自己也在用；后面那个不清楚，可以自行测试

**Comment by bestRunner** [comment]
> > 使用的是：UserByRestId，UserByScreenName和1.1/users/show.json这三个接口进行采集的
> 
> 这三个是以前的网页用的接口，前两个可以用我上面给的那个 `bearer token` 获取 `guest_token `来调用，应该是没有问题的，我自己也在用；后面那个不清楚，可以自行测试

这个 `bearer token` 是移动端的吗
